
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

export const collections = {
  /**
   * Marketing
   */
  marketing: {
    codename: "marketing",
    id: "",
    name: "Marketing",
  },

  /**
   * Client Advisory
   */
  client_advisory: {
    codename: "client_advisory",
    id: "",
    name: "Client Advisory",
  },

  /**
   * Trading & Markets
   */
  trading___markets: {
    codename: "trading___markets",
    id: "",
    name: "Trading & Markets",
  },

  /**
   * Risk Management
   */
  risk_management: {
    codename: "risk_management",
    id: "",
    name: "Risk Management",
  },

  /**
   * Compliance
   */
  compliance: {
    codename: "compliance",
    id: "",
    name: "Compliance",
  },

  /**
   * Default
   */
  default: {
    codename: "default",
    id: "00000000-0000-0000-0000-000000000000",
    name: "Default",
  },
} as const;
